# Generated by Django 5.2.7 on 2025-11-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='photos/', verbose_name='写真')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='サムネイル')),
                ('message', models.TextField(blank=True, default='コメントなし', verbose_name='投稿者コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='写真へのコメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='コメント投稿日時')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageboard.photo', verbose_name='写真')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
